################################################################################
## Copyright (C) 2026 Potsdam Institute for Climate Impact Research (PIK),    ##
## see COPYRIGHT file.                                                        ##
##                                                                            ##
## This file is part of LandInG and licensed under GNU AGPL Version 3 or      ##
## later. See LICENSE file or go to http://www.gnu.org/licenses/              ##
## Contact: https://github.com/PIK-LPJmL/LandInG/                             ##
################################################################################

################################################################################
## This function tries to update country-level data generated by LandInG      ##
## version 1.0.0 to version 1.1.0                                             ##
## Parameters:                                                                ##
## country_env: environment containing data read from RData file              ##
## LandInG_version: target LandInG_version                                    ##
## fao_mon_country_objects: optional character string with variable names in  ##
##                          country_env or NULL                               ##
## Returns fao_mon_country_objects if not NULL, otherwise returns country_env ##
## invisibly.                                                                 ##
################################################################################
update_country_data <- function(country_env,
                                LandInG_version,
                                fao_mon_country_objects = NULL
                               ) {
  if (is.null(country_env$LandInG_version)) {
    country_env$LandInG_version <- "1.0.0"
  }
  if (country_env$LandInG_version != LandInG_version) {
    warning(
      "Imported data from country_level_data.R was generated with a different ",
      "version of LandInG: ", country_env$LandInG_version, " (imported) != ",
      LandInG_version, " (current script)\n",
      "Trying to fix. Consider re-running country_level_data.R",
      immediate. = TRUE
    )
    # Try to fix variables that have been renamed from previous LandInG version
    for (
      name in c(
        "fao_mon_production_array",
        "fao_mon_use_pattern",
        "fao_mon_production_group_members"
      )
    ) {
      orig <- sub("_mon_", "_monfreda_", name)
      if (is.null(country_env[[name]]) &&
          !is.null(country_env[[orig]])
      ) {
        message("Rename imported ", sQuote(orig), " to ", sQuote(name))
        country_env[[name]] <- country_env[[orig]]
        rm(list = orig, envir = country_env)
        if (!is.null(fao_mon_country_objects)) {
          fao_mon_country_objects <- sub(
            orig,
            name,
            fao_mon_country_objects,
            fixed = TRUE
          )
        }
      }
    }
    for (name in grep("^ramankutty_", names(country_env), value = TRUE)) {
      repl <- sub("^ramankutty_", "ram_", name)
      if (is.null(country_env[[repl]])) {
        message("Rename imported ", sQuote(name), " to ", sQuote(repl))
        country_env[[repl]] <- country_env[[name]]
        rm(list = name, envir = country_env)
        if (!is.null(fao_mon_country_objects)) {
          fao_mon_country_objects <- sub(
            name,
            repl,
            fao_mon_country_objects,
            fixed = TRUE
          )
        }
      }
    }
    for (name in grep("^monfreda_", names(country_env), value = TRUE)) {
      repl <- sub("^monfreda_", "mon_", name)
      if (is.null(country_env[[repl]])) {
        message("Rename imported ", sQuote(name), " to ", sQuote(repl))
        country_env[[repl]] <- country_env[[name]]
        rm(list = name, envir = country_env)
        if (!is.null(fao_mon_country_objects)) {
          fao_mon_country_objects <- sub(
            name,
            repl,
            fao_mon_country_objects,
            fixed = TRUE
          )
        }
      }
    }
    # Try to add dimension names for backwards compatibility with version 1.0.0.
    if (
      !is.null(country_env$fao_mon_production_array) &&
        is.null(names(dimnames(country_env$fao_mon_production_array)))
    ) {
      message("Add dimension names to 'fao_mon_production_array'")
      dn <- dimnames(country_env$fao_mon_production_array)
      names(dim(country_env$fao_mon_production_array)) <- names(dn) <-
        c("country", "item", "time", "value")
      dimnames(country_env$fao_mon_production_array) <- dn
    }
    if (
      !is.null(country_env$fao_mon_use_pattern) &&
        is.null(names(dimnames(country_env$fao_mon_use_pattern)))
    ) {
      message("Add dimension names to 'fao_mon_use_pattern'")
      dn <- dimnames(country_env$fao_mon_use_pattern)
      names(dim(country_env$fao_mon_use_pattern)) <- names(dn) <-
        c("country", "item", "time")
      dimnames(country_env$fao_mon_use_pattern) <- dn
    }
    if (
      !is.null(country_env$fao_mon_production_group_members) &&
        is.null(names(dimnames(country_env$fao_mon_production_group_members)))
    ) {
      message("Add dimension names to 'fao_mon_production_group_members'")
      dn <- dimnames(country_env$fao_mon_production_group_members)
      names(dim(country_env$fao_mon_production_group_members)) <- names(dn) <-
        c("country", "group", "time", "dataset")
      dimnames(country_env$fao_mon_production_group_members) <- dn
    }
    if (
      !is.null(country_env$production_array_filled) &&
        is.null(names(dimnames(country_env$production_array_filled)))
    ) {
      message("Add dimension names to 'production_array_filled'")
      dn <- dimnames(country_env$production_array_filled)
      names(dim(country_env$production_array_filled)) <- names(dn) <-
        c("country", "item", "element", "time")
      dimnames(country_env$production_array_filled) <- dn
    }
    if (
      !is.null(country_env$landuse_array_expanded) &&
        is.null(names(dimnames(country_env$landuse_array_expanded)))
    ) {
      message("Add dimension names to 'landuse_array_expanded'")
      dn <- dimnames(country_env$landuse_array_expanded)
      names(dim(country_env$landuse_array_expanded)) <- names(dn) <-
        c("country", "item", "element", "time")
      dimnames(country_env$landuse_array_expanded) <- dn
    }
    if (
      !is.null(country_env$production_array_gapfilling) &&
        is.null(names(dimnames(country_env$production_array_gapfilling)))
    ) {
      message("Add dimension names to 'production_array_gapfilling'")
      dn <- dimnames(country_env$production_array_gapfilling)
      names(dim(country_env$production_array_gapfilling)) <- names(dn) <-
        c("country", "item", "time")
      dimnames(country_env$production_array_gapfilling) <- dn
    }
  }
  # Convert Raster objects from version 1.0.0 for backwards compatibility.
  for (obj in names(country_env)) {
    if (any(class(country_env[[obj]]) %in%
        c("RasterLayer", "RasterStack", "RasterBrick"))
    ) {
      if (all(c("raster", "terra") %in% .packages(all.available = TRUE))) {
        country_env[[obj]] <- as(country_env[[obj]], "SpatRaster")
      } else {
        warning(
          "Cannot convert ", sQuote(obj), " to SpatRaster",
          immediate. = TRUE
        )
      }
    }
  }
  # Return fao_mon_country_objects if not NULL
  if (!is.null(fao_mon_country_objects)) {
    fao_mon_country_objects
  } else {
    invisible(country_env)
  }
}
