################################################################################
## Copyright (C) 2022 Potsdam Institute for Climate Impact Research (PIK),    ##
## see COPYRIGHT file.                                                        ##
##                                                                            ##
## This file is part of LandInG and licensed under GNU AGPL Version 3 or      ##
## later. See LICENSE file or go to http://www.gnu.org/licenses/              ##
## Contact: https://github.com/PIK-LPJmL/LandInG/                             ##
################################################################################

################################################################################
## This script converts absolute gridded harvested areas from Monfreda into   ##
## cropping intensities by dividing them by cropland extent from Ramankutty.  ##
## Since HYDE cropland used in the toolbox differs from Ramankutty cropland a ##
## spatial gap-filling of cropping intensities is conducted to make all       ##
## cropland cells are covered.                                                ##
## Run country_level_data.R before this script.                               ##
################################################################################

# Clean up memory
rm(list = ls(all = TRUE))

################################################################################
## Setup of variables valid across all scripts related to land use data       ##
## processing.                                                                ##
## - sets many directories and file names                                     ##
## - also loads several helper functions used by various land use processing  ##
##   scripts                                                                  ##
source("landuse_setup.R")
################################################################################

################################################################################
## Crop re-assignment                                                         ##
## Some FAOSTAT crops have no direct corresponding crop in Monfreda but       ##
## another crop's pattern can be used, e.g. FAOSTAT has harvested areas for   ##
## Kapok fruit (and no harvested areas for the products Kapok fibre and Kapok ##
## seeds) while Monfreda has harvested areas for Kapok fibre and Kapok seeds. ##
## - Name of the list item: FAOSTAT crop that should use pattern(s) from a    ##
##   different crop
## - Value of the list item: FAOSTAT crop whose Monfreda pattern(s) should be ##
##   used instead (make sure that Monfreda has those crops)                   ##
fao_reassign <- list(
  "Kapok fruit" = "Kapok fibre",
  "Fruit, pome nes" = c("Apples", "Pears", "Quinces")
)
################################################################################


################################################################################
## Load results of country level processing from predecessor scripts.         ##
cat(
  "Loading results generated by country_level_data.R from:",
  toString(
    sQuote(
      c(LandInG_setup$landuse$fao_mon_country_RData,
        LandInG_setup$landuse$mon_gadm_sums_RData)
    )
  ),
  "\n"
)
country_env <- new.env()
# Monfreda gridded harvested areas aggregated to GADM countries
load(LandInG_setup$landuse$mon_gadm_sums_RData, envir = country_env)
# Country sums of matching Monfreda and FAOSTAT crops; track variables added
# from RData file for later update
loaded_objects <- ls(envir = country_env)
load(LandInG_setup$landuse$fao_mon_country_RData, envir = country_env)
fao_mon_country_objects <- setdiff(ls(envir = country_env), loaded_objects)
rm(loaded_objects)
# Check loaded data for correct LandInG version and try to update data if
# generated by earlier LandInG version.
fao_mon_country_objects <- update_country_data(
  country_env,
  LandInG_setup$LandInG_version,
  fao_mon_country_objects
)
# Unwrap SpatRaster objects.
for (obj in names(country_env)) {
  if (any(class(country_env[[obj]]) == "PackedSpatRaster")) {
    country_env[[obj]] <- terra::unwrap(country_env[[obj]])
  }
}
################################################################################


################################################################################
## Load GADM data and check if global                                         ##
## GADM is used to assign grid cells to administrative areas. The file        ##
## gadmlevel_file is generated by scripts in ../gadm so make sure to run      ##
## these first.                                                               ##
cat(
  "Loading gridded GADM administrative unit data from",
  sQuote(LandInG_setup$landuse$gadmlevel_file), "\n"
)
gadmlevel_raster <- terra::rast(LandInG_setup$landuse$gadmlevel_file)
terra::set.names(gadmlevel_raster, c("country", "state", "district"))
gadmlevel_names <- read.csv(
  LandInG_setup$landuse$gadmlevel_names_file,
  stringsAsFactors = FALSE,
  comment.char = "#"
)
# Select country data from gadmlevel_names
index <- which(!is.na(gadmlevel_names$level0_ID))
cols <- c("level0_ID", "level0_code", "country")
gadm_country_names <- gadmlevel_names[index, cols]

for (rastercheck in c("gadmlevel_raster")) {
  tmpraster <- get(rastercheck)
  if (matching_extent(
    terra::ext(tmpraster),
    global_extent,
    terra::xres(tmpraster),
    terra::yres(tmpraster)
  )) {
    terra::ext(tmpraster) <- global_extent
  }
  assign(rastercheck, tmpraster)
}
################################################################################

################################################################################
## Load various FAOSTAT definitions and do some consistency checks.           ##
cat(
  "FAOSTAT crop item definitions loaded from",
  toString(
    sQuote(
      c(LandInG_setup$landuse$fao_production_item_file,
        LandInG_setup$landuse$fao_production_item_group_file)
    )
  ),
  "\n"
)
fao_production_item_def <- data.table::fread(
  LandInG_setup$landuse$fao_production_item_file,
  na.strings = "...",
  # country code for Namibia is "NA", which would normally be converted into NA
  check.names = TRUE,
  data.table = FALSE,
  header = TRUE
)
fao_production_item_group_def <- data.table::fread(
  LandInG_setup$landuse$fao_production_item_group_file,
  na.strings = "...",
  # country code for Namibia is "NA", which would normally be converted into NA
  check.names = TRUE,
  data.table = FALSE,
  header = TRUE
)
# Changes in country definitions over time
cat(
  "FAO country definitions loaded from:",
  toString(
    sQuote(
      c(LandInG_setup$landuse$fao_production_country_file,
        LandInG_setup$landuse$fao_production_country_group_file)
    )
  ),
  "\n"
)
fao_production_country_def <- data.table::fread(
  LandInG_setup$landuse$fao_production_country_file,
  na.strings = "...",
  # country code for Namibia is "NA", which would normally be converted into NA
  check.names = TRUE,
  data.table = FALSE,
  header = TRUE
)
fao_production_country_group_def <- data.table::fread(
  LandInG_setup$landuse$fao_production_country_group_file,
  na.strings = "...",
  # country code for Namibia is "NA", which would normally be converted into NA
  check.names = TRUE,
  data.table = FALSE,
  header = TRUE
)
# FAOSTAT to GADM country mapping

cat(
  "FAO to GADM mapping:",
  toString(sQuote(LandInG_setup$landuse$fao_gadm_mapping_file)),
  "\n"
)
for (filename in LandInG_setup$landuse$fao_gadm_mapping_file) {
  source(filename)
}
# Crop type mapping between FAOSTAT, MIRCA, and Monfreda
cat(
  "Crop type mapping:",
  toString(LandInG_setup$landuse$mapping_file),
  "\n"
)
crop_type_mapping <- read.csv(
  LandInG_setup$landuse$mapping_file,
  stringsAsFactors = FALSE,
  comment.char = "#"
)
# Clean encoding
message("Converting special characters read from text files if necessary.")
for (table in c(
  "fao_production_country_def",
  "fao_production_item_group_def",
  "gadmlevel_names",
  "crop_type_mapping",
  "fao_production_country_group_def",
  "fao_production_item_def",
  "gadm_country_names"
)) {
  if (!exists(table))
    next
  table_data <- get(table)
  for (c in colnames(table_data)) {
    if (typeof(table_data[, c]) == "character") {
      if (!all(stringi::stri_enc_isascii(table_data[, c]), na.rm = TRUE)) {
        # String has non-ASCII characters
        if (!all(stringi::stri_enc_isutf8(table_data[, c]), na.rm = TRUE)) {
          # String has non-UTF8 characters -> assume windows-1252 encoding and
          # convert to UTF-8
          message(
            "Converting column ", sQuote(c),
            " from windows-1252 to UTF-8 encoding in ", table
          )
          table_data[, c] <- stringi::stri_encode(
            table_data[, c],
            "windows-1252",
            "UTF-8"
          )
        }
        # Convert UTF-8 strings to ASCII strings, if necessary translating
        # special characters
        message(
          "Converting column ", sQuote(c),
          " from UTF-8 to ASCII encoding in ", table
        )
        table_data[, c] <- stringi::stri_encode(
          table_data[, c],
          "UTF-8",
          "UTF-8"
        )
        table_data[, c] <- stringi::stri_trans_general(
          table_data[, c],
          "latin-ascii"
        )
      }
    }
  }
  assign(table, table_data)
}
# Check consistency between compound_countries and fao_production_country_def
index <- which(!is.na(fao_production_country_def$End.Year))
mismatch <- setdiff(
  names(LandInG_setup$landuse$compound_countries),
  fao_production_country_def$Country[index]
)
if (length(mismatch) > 0) {
  # compound_countries has countries not mentioned in
  # fao_production_country_def, remove
  for (c in mismatch) {
    LandInG_setup$landuse$compound_countries[[c]] <- NULL
  }
}
mismatch <- setdiff(
  fao_production_country_def$Country[index],
  names(LandInG_setup$landuse$compound_countries)
)
if (length(mismatch) > 0) {
  for (country in mismatch) {
    index <- which(fao_production_country_def$Country == country)
    warning(
      sQuote(country),
      " is missing in compound_countries but is listed as ceasing to exist in ",
      fao_production_country_def[index, "End.Year"],
      call. = FALSE,
      immediate. = TRUE
    )
  }
}
# Determine country groups
fao_groups <- list()
# Combine all FAOSTAT country definitions
# Names sometimes differ between different definition lists
clist <- data.table::setDF(
  # Temporarily convert to data.table because data.frames with different
  # colnames cannot be merged using rbind.
  rbind(
    data.table::setDT(
      fao_production_country_def[, c("Country", "Country.Code")]
    ),
    data.table::setDT(
      fao_production_country_group_def[, c("Country", "Country.Code")]
    ),
    data.table::setDT(
      fao_production_country_group_def[, c("Country.Group", "Country.Group.Code")]
    ),
    use.names = FALSE
  )
)
# Find countries from fao_mon_production_array.
# match returns first occurrence in case of several occurrences
index1 <- match(
  dimnames(country_env$fao_mon_production_array)[["country"]],
  clist[, 1]
)
for (group_code in intersect(
  clist[index1, 2],
  fao_production_country_group_def$Country.Group.Code
)) {
  # Find FAOSTAT indices of countries belonging to group in
  # fao_production_country_group_def
  index2 <- which(
    fao_production_country_group_def$Country.Group.Code == group_code
  )
  # FAOSTAT codes of countries belonging to group in
  # fao_production_country_group_def
  group_country_codes <- fao_production_country_group_def$Country.Code[index2]
  # Indices of countries in fao_production_country_group_def
  index3 <- match(
    group_country_codes,
    fao_production_country_group_def$Country.Code
  )
  # Country names in clist (first occurrence of group_country_codes in clist)
  group_country_names <- ifelse(
    group_country_codes %in% as.integer(clist[, 2]),
    clist[match(group_country_codes, as.integer(clist[, 2])), 1],
    fao_production_country_group_def$Country[index3]
  )
  # Find group_code in fao_production_country_group_def
  index4 <- match(
    group_code,
    fao_production_country_group_def$Country.Group.Code
  )
  # Group name of group_code according to
  # fao_production_country_group_def
  tmpname <- fao_production_country_group_def$Country.Group[index4]
  fao_groups[[tmpname]] <- group_country_names
}
cat("*** Filling country groups in FAOSTAT to GADM country mapping ***\n")
cat("Country groups derived from fao_production_country_group_def\n")
for (country in names(fao_groups)) {
  cat("Filling", country, "in GADM country list\n")
  LandInG_setup$landuse$fao_gadm_country_mapping[[country]] <- unique(
    unlist(LandInG_setup$landuse$fao_gadm_country_mapping[fao_groups[[country]]])
  )
}
# Countries in GADM without corresponding FAOSTAT countries
mismatch <- which(
  !gadm_country_names$level0_code %in%
    unlist(LandInG_setup$landuse$fao_gadm_country_mapping)
)
if (length(mismatch) > 0) {
  cat(
    "The following GADM units have no corresponding FAO country:",
    toString(sQuote(gadm_country_names$country[mismatch])), "\n"
  )
  if ("World" %in% names(LandInG_setup$landuse$fao_gadm_country_mapping)) {
    cat("Adding them to FAO country group 'World'\n")
    LandInG_setup$landuse$fao_gadm_country_mapping[["World"]] <- c(
      LandInG_setup$landuse$fao_gadm_country_mapping[["World"]],
      gadm_country_names$level0_code[mismatch]
    )
  }
}
# Remove potential duplicates in fao_gadm_country_mapping
# There are currently some duplicates in fao_gadm_country_mapping.R because
# FAOSTAT renamed some countries recently and we keep old names for backwards
# compatibility.
for (country in setdiff(
  names(LandInG_setup$landuse$fao_gadm_country_mapping),
  dimnames(country_env$fao_mon_production_array)[["country"]]
)) {
  # Country from fao_gadm_country_mapping not found in
  # fao_mon_production_array
  # Look for entries in fao_gadm_country_mapping with same countries
  cindex <- match(
    country,
    names(LandInG_setup$landuse$fao_gadm_country_mapping)
  )
  dupl <- which(
    sapply(
      LandInG_setup$landuse$fao_gadm_country_mapping[-cindex],
      identical,
      y = LandInG_setup$landuse$fao_gadm_country_mapping[[country]]
    )
  )
  if (length(dupl) > 0) {
    cat(
      "Removing", sQuote(country),
      "from fao_gadm_country_mapping because it seems to be a duplicate of",
      toString(sQuote(names(dupl))), "\n"
    )
    LandInG_setup$landuse$fao_gadm_country_mapping[[country]] <- NULL
    # Also remove from compound_countries
    LandInG_setup$landuse$compound_countries <- sapply(
      LandInG_setup$landuse$compound_countries,
      setdiff,
      y = country
    )
  }
}
# Now check again for duplicates
for (country in names(LandInG_setup$landuse$fao_gadm_country_mapping)) {
  cindex <- match(
    country,
    names(LandInG_setup$landuse$fao_gadm_country_mapping)
  )
  dupl <- which(
    sapply(
      LandInG_setup$landuse$fao_gadm_country_mapping[-cindex],
      identical,
      y = LandInG_setup$landuse$fao_gadm_country_mapping[[country]]
    )
  )
  if (length(dupl) > 0) {
    warning(
      sQuote(country), " seems to be a duplicate of ",
      toString(sQuote(names(dupl))), " in fao_gadm_country_mapping\n",
      call. = FALSE,
      immediate. = TRUE
    )
  }
}
# Check consistency of crop names
# Check 1 (Monfreda names)
mismatch <- setdiff(LandInG_setup$landuse$mon_names, crop_type_mapping$Monfreda)
if (length(mismatch) > 0) {
  stop(
    "Monfreda crop(s) ",
    toString(sQuote(mismatch)),
    " are missing in crop_type_mapping.\n",
    "Please update ", sQuote(LandInG_setup$landuse$mapping_file)
  )
}
# Check 2 (Monfreda names)
mismatch <- setdiff(crop_type_mapping$Monfreda, LandInG_setup$landuse$mon_names)
if (length(mismatch) > 0) {
  stop(
    "crop_type_mapping contains ",
    length(mismatch), " crops not included in mon_names: ",
    toString(mismatch), "\n",
    "Please update ", sQuote(LandInG_setup$landuse$mapping_file)
  )
}
# Check 3 (names in fao_mon_production_array)
# Crops from fao_mon_production_array which are not individual FAOSTAT
# crops
tmpcrops <- setdiff(
  dimnames(country_env$fao_mon_production_array)[["item"]],
  c(fao_production_item_group_def$Item, fao_production_item_def$Item)
)
if (length(tmpcrops) > 0) {
  # Check 4: Crops which are neither individual FAOSTAT crops nor FAOSTAT crop
  # group
  tmpcrops2 <- setdiff(tmpcrops, fao_production_item_group_def$Item.Group)
  if (length(tmpcrops2) > 0) {
    message(
      length(tmpcrops2),
      " crop names in fao_mon_production_array are not defined as either",
      " crops or crop groups in fao_production_item_group_def or",
      " fao_production_item_def"
    )
    # Check if these crops are Monfreda names
    if (length(setdiff(tmpcrops2, LandInG_setup$landuse$mon_names)) > 0) {
      # Abort if there are undefined crops
      stop(
        "The following crops in fao_mon_production_array are neither ",
        "defined as FAOSTAT crops/crop groups in ",
        "fao_production_item_group_def or ",
        "fao_production_item_def nor as Monfreda crops: ",
        toString(
          sQuote(setdiff(tmpcrops2, LandInG_setup$landuse$mon_names))
        ),
        "\nPlease check processing in predecessor scripts."
      )
    }
    index <- match(tmpcrops2, crop_type_mapping$Monfreda)
    mismatch <- which(! is.na(crop_type_mapping$FAO.item.code[index]))
    if (length(mismatch) == 0) {
      # These crops are Monfreda crops and should not have FAOSTAT item codes
      # according to mapping_file. All good.
      message(
        "They are Monfreda crops with no matching FAOSTAT crop according to ",
        "crop_type_mapping"
      )
    } else {
      # These are Monfreda crops but they should be included in FAOSTAT
      # according to mapping_file.
      warning(
        "Inconsistency between Monfreda and FAOSTAT lists: ",
        toString(sQuote(tmpcrops2[mismatch])),
        " has/have FAO item code according to crop_type_mapping but is/are",
        " missing in fao_production_item_group_def and",
        " fao_production_item_def.\nPlease check ",
        sQuote(LandInG_setup$landuse$mapping_file),
        call. = FALSE,
        immediate. = TRUE
      )
    }
  }
  rm(tmpcrops2)
}
rm(tmpcrops)
# Re-assignment rules
mismatch <- setdiff(
  names(fao_reassign),
  dimnames(country_env$fao_mon_production_array)[["item"]]
)
if (length(mismatch) > 0) {
  warning(
    "There are re-assignment rules for crops ",
    toString(sQuote(mismatch)),
    " but the crops are not found in fao_mon_production_array.\n",
    "Please check if crop names have changed.",
    call. = FALSE,
    immediate. = TRUE
  )
}
# Check if datasets are absolute areas or fractions
hyde_is_fraction <- !units::ud_are_convertible(
  LandInG_setup$landuse$hyde_area_units,
  "m2"
)
mon_is_fraction <- !units::ud_are_convertible(
  LandInG_setup$landuse$mon_area_units,
  "m2"
)
fao_is_fraction <- !units::ud_are_convertible(
  LandInG_setup$landuse$fao_area_units,
  "m2"
)
ram_is_fraction <- !units::ud_are_convertible(
  LandInG_setup$landuse$ram_units,
  "m2"
)
################################################################################


################################################################################
## Load HYDE data                                                             ##
# HYDE area file is aggregated to the resolution of unitraster if necessary
hyde_area <- load_hyde_area(
  filename = LandInG_setup$landuse$hyde_area_file,
  fileunits = LandInG_setup$landuse$hyde_area_file_units,
  return_units = LandInG_setup$landuse$fao_area_units,
  return_raster = NULL, # set to NULL to get native HYDE resolution
  earth_radius = LandInG_setup$earthradius,
  gextent = global_extent
)
hyde_area <- hyde_area$area
if (matching_extent(
  terra::ext(hyde_area),
  terra::ext(country_env$ram_gadm_cropland),
  terra::xres(hyde_area),
  terra::yres(hyde_area)
)) {
  hyde2gadm <- round(
    terra::res(country_env$ram_gadm_cropland) / terra::res(hyde_area),
    4
  )
  if (max(hyde2gadm %% 1) != 0) {
    stop(
      "Target resolution ",
      toString(round(terra::res(country_env$ram_gadm_cropland), 5)),
      " is not an integer multiple of HYDE resolution ",
      toString(round(terra::res(hyde_area), 5)), "\n",
      "Cannot aggregate."
    )
  }
  if (min(hyde2gadm) < 1) {
    stop(
      "Target resolution ",
      toString(round(terra::res(country_env$ram_gadm_cropland), 5)),
      " is finer than HYDE resolution ",
      toString(round(terra::res(hyde_area), 5)), "\n",
      "Output resolution cannot be finer than any gridded source data."
    )
  } else if (max(hyde2gadm) == 1) {
    hyde_target_area <- hyde_area
  } else {
    hyde_target_area <- terra::aggregate(
      hyde_area,
      fact = rev(hyde2gadm), # res() returns lon/lat, fact is lat/lon
      fun = "sum",
      na.rm = TRUE
    )
    terra::units(hyde_target_area) <- terra::units(hyde_area)
    if (
      !isTRUE(
        all.equal(
          terra::global(hyde_target_area, "sum", na.rm = TRUE),
          terra::global(hyde_area, "sum", na.rm = TRUE)
        )
      )
    ) {
      # Global area sum before and after aggregation do not match
      stop("Error aggregating hyde_area to target resolution")
    }
  }
} else {
  stop(
    "Spatial extent of ", sQuote(LandInG_setup$landuse$hyde_area_file),
    " does not match spatial extent of Ramankutty cropland/Monfreda",
    " harvested areas"
  )
}
# HYDE maximum cropland extent
# Maximum cropland is saved to file to reduce runtime if the script is run
# again for the same resolution and time period
if (!file.exists(LandInG_setup$landuse$hyde_max_cropland_filename)) {
  # Create file if it does not exist yet
  # This requires CDO tools to be installed and accessible. Syntax in
  # helper/create_hyde_timeseries_max.R is for Linux.
  create_hyde_timeseries_max(
    source = LandInG_setup$landuse$hyde_cropland_filename,
    target = LandInG_setup$landuse$hyde_max_cropland_filename,
    varname = LandInG_setup$landuse$hyde_cropland_varname,
    sourcearea = hyde_area,
    targetarea = hyde_target_area,
    area_units = LandInG_setup$landuse$hyde_area_units
  )
}
if (file.exists(LandInG_setup$landuse$hyde_max_cropland_filename)) {
  cat(
    "Loading maximum cropland extent from",
    sQuote(LandInG_setup$landuse$hyde_max_cropland_filename), "\n"
  )
  hyde_max_cropland <-
    terra::rast(LandInG_setup$landuse$hyde_max_cropland_filename)
  unit <- terra::units(hyde_max_cropland)
  if (units::ud_convert(1, LandInG_setup$landuse$hyde_area_units, unit) != 1) {
    warning(
      "Unit in file ", sQuote(LandInG_setup$landuse$hyde_max_cropland_filename),
      " [", unit, "] differs from defined hyde_area_units [",
      LandInG_setup$landuse$hyde_area_units,
      "].",
      call. = FALSE,
      immediate. = TRUE
    )
    # update unit
    LandInG_setup$landuse$hyde_area_units <- unit
    hyde_is_fraction <-
      !units::ud_are_convertible(LandInG_setup$landuse$hyde_area_units, "m2")
  }
  if (hyde_is_fraction) {
    hyde_max_cropland <- hyde_max_cropland *
      units::ud_convert(1, LandInG_setup$landuse$hyde_area_units, "1") *
      hyde_target_area
    terra::units(hyde_max_cropland) <- terra::units(hyde_target_area)
  } else {
    hyde_max_cropland <- hyde_max_cropland *
      units::ud_convert(1, unit, LandInG_setup$landuse$fao_area_units)
    terra::units(hyde_max_cropland) <- LandInG_setup$landuse$fao_area_units
  }
} else {
  stop(
    sQuote(LandInG_setup$landuse$hyde_max_cropland_filename),
    " does not exist and cannot be created automatically."
  )
}
################################################################################

################################################################################
## Convert Monfreda gridded harvested areas into cropping intensities.        ##
## This loops over the crop names in fao_mon_production_array (mostly    ##
## FAOSTAT crop names) and finds the corresponding Monfreda crop (or crops),  ##
## taking into account any crop re-assignments defined above.                 ##
##                                                                            ##
# Determine filenames
mon_filenames <- character(length(LandInG_setup$landuse$mon_names))
names(mon_filenames) <- LandInG_setup$landuse$mon_names
for (crop in LandInG_setup$landuse$mon_names) {
  tmpnames <- file.path(
    dir(
      LandInG_setup$landuse$mon_datadir[LandInG_setup$landuse$mon_fmt],
      pattern = paste0("^", crop, "_HarvAreaYield"),
      full.names = TRUE
    ),
    paste0(
      crop, "_",
      LandInG_setup$landuse$mon_file_var[[LandInG_setup$landuse$mon_fmt]][1],
      ".",
      LandInG_setup$landuse$mon_file_ext[LandInG_setup$landuse$mon_fmt]
    )
  )
  if (length(which(file.exists(tmpnames))) != 1) {
    stop(
      paste0(
        "Cannot determine filename for crop ", sQuote(crop), ".\n",
        "Tested filename(s): ", toString(tmpnames)
      )
    )
  }
  mon_filenames[crop] <- tmpnames[which(file.exists(tmpnames))]
  rm(tmpnames)
}
# Check that extent and resolution match (including the need to aggregate
# Monfreda data)
# Check which mon_filenames actually exist
index <- min(which(file.exists(mon_filenames)))
if (is.finite(index)) {
  # Derive extent and resolution of Monfreda files
  mon_raster <- terra::rast(mon_filenames[1])
  if (matching_extent(
    terra::ext(mon_raster),
    global_extent,
    terra::xres(mon_raster),
    terra::yres(mon_raster)
  )) {
    terra::ext(mon_raster) <- global_extent
  }
} else {
  stop("No matching Monfreda crop file found. Check settings in landuse_setup.R")
}
if (
  any(
    terra::res(mon_raster) < terra::res(LandInG_setup$landuse$gadm_raster)
  )
) {
  # Aggregation factor
  mon2gadm <- round(
    terra::res(LandInG_setup$landuse$gadm_raster) / terra::res(mon_raster),
    4
  )
  if (max(mon2gadm %% 1) != 0) {
    stop(
      "GADM resolution ",
      toString(round(terra::res(LandInG_setup$landuse$gadm_raster), 5)),
      " is not an integer multiple of ",
      "Monfreda resolution ", toString(round(terra::res(mon_raster), 5)),
      "\nCannot aggregate."
    )
  }
} else if (
  any(
    terra::res(mon_raster) / terra::res(LandInG_setup$landuse$gadm_raster) >
      1.00001
  )
) {
  stop(
    "GADM resolution ",
    toString(round(terra::res(LandInG_setup$landuse$gadm_raster), 5)),
    " is finer than Monfreda resolution ",
    toString(round(terra::res(mon_raster), 5)), "\n",
    "Output resolution cannot be finer than any gridded source data."
  )
} else {
  mon2gadm <- c(1, 1)
}
rm(mon_raster)
# Cropping intensities are saved as a NetCDF in the resolution-specific
# working_dir
cat(
  "Generating", sQuote(LandInG_setup$landuse$harvested_fraction_filename),
  "which contains for each crop the harvested area expressed as a fraction",
  "of physical cropland.\n"
)
croplist <- intersect(
  dimnames(country_env$fao_mon_production_array)[["item"]],
  fao_production_item_group_def$Item.Group
)
cat(
  "A total of", dim(country_env$fao_mon_production_array)[2],
  "crops of which", length(croplist), "are FAOSTAT groups\n"
)
# Check for cells with HYDE cropland but no Ramankutty cropland. These require
# gap-filling.
mismatch <- list()
for (year in seq_along(LandInG_setup$landuse$mon_refyear)) {
  mismatch[[as.character(LandInG_setup$landuse$mon_refyear[year])]] <- which(
    terra::values(hyde_max_cropland, mat = FALSE) > 0 &
      (
        terra::values(country_env$ram_gadm_cropland[[year]], mat = FALSE) == 0 |
          is.na(
            terra::values(country_env$ram_gadm_cropland[[year]], mat = FALSE)
          )
      )
  )
}
cat(
  "As part of the process, a gap-filling is attempted for the",
  max(sapply(mismatch, length)),
  "cells which feature cropland according to HYDE but have",
  "no cropland/harvested area information according to Ramankutty/Monfreda\n"
)
cat(
  "Gap-filling statistics saved to",
  sQuote(LandInG_setup$landuse$harvested_fraction_fill_statistics_RData), "\n"
)

if (!file.exists(LandInG_setup$landuse$harvested_fraction_filename)) {
  # Create harvested_fraction_filename if it does not exist yet
  # Define NetCDF dimensions
  londim <- ncdf4::ncdim_def(
    name = "lon",
    units = "degrees_east",
    vals = terra::xFromCol(country_env$ram_gadm_cropland),
    longname = "longitude"
  )
  latdim <- ncdf4::ncdim_def(
    name = "lat",
    units = "degrees_north",
    vals = terra::yFromRow(country_env$ram_gadm_cropland),
    longname = "latitude"
  )
  cropdim <- ncdf4::ncdim_def(
    name = "crop",
    units = "",
    vals = seq_len(dim(country_env$fao_mon_production_array)[2]),
    create_dimvar = FALSE
  )
  nchardim <- ncdf4::ncdim_def(
    name = "nchar",
    units = "",
    vals = seq_len(
      max(nchar(dimnames(country_env$fao_mon_production_array)[["item"]]))
    ),
    create_dimvar = FALSE
  )
  timedim <- ncdf4::ncdim_def(
    name = "time",
    units = paste0(
      "years since ",
      min(LandInG_setup$landuse$mon_refyear), "-01-01"
    ),
    vals = LandInG_setup$landuse$mon_refyear -
      min(LandInG_setup$landuse$mon_refyear)
  )

  # Define NetCDF variables
  harvested_fraction_var <- ncdf4::ncvar_def(
    name = "harvested_fraction",
    units = "",
    dim = list(londim, latdim, cropdim, timedim),
    missval = -1e20,
    longname = "Harvested area share of total cropland in cell"
  )
  crop_var <- ncdf4::ncvar_def(
    name = "crop",
    units = "",
    dim = list(nchardim, cropdim),
    longname = "crop name",
    prec = "char"
  )
  harvested_fraction_file <- ncdf4::nc_create(
    filename = LandInG_setup$landuse$harvested_fraction_filename,
    vars = list(harvested_fraction_var, crop_var),
    force_v4 = TRUE
  )
  # Write crop names to file
  ncdf4::ncvar_put(
    nc = harvested_fraction_file,
    varid = "crop",
    vals = dimnames(country_env$fao_mon_production_array)[["item"]]
  )
  # Version information
  ncdf4::ncatt_put(
    nc = harvested_fraction_file,
    varid = 0,
    attname = "LandInG_version",
    attval = LandInG_setup$LandInG_version
  )

  # Write NAs to file to make sure crops are processed
  for (crop in seq_len(dim(country_env$fao_mon_production_array)[2])) {
    ncdf4::ncvar_put(
      nc = harvested_fraction_file,
      varid = "harvested_fraction",
      vals = rep(NA, londim$len * latdim$len * timedim$len),
      start = c(1, 1, crop, 1),
      count = c(-1, -1, 1, -1)
    )
  }
  ncdf4::nc_sync(harvested_fraction_file)
} else {
  # If harvested_fraction_file exists already try reusing it and only process
  # crops that have not been processed yet
  cat("Continuing previous script run\n")
  harvested_fraction_file <- ncdf4::nc_open(
    LandInG_setup$landuse$harvested_fraction_filename,
    write = TRUE
  )
  atts <- ncdf4::ncatt_get(harvested_fraction_file, varid = 0)
  if (is.null(atts[["LandInG_version"]])) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "File ",
      sQuote(LandInG_setup$landuse$harvested_fraction_filename),
      " was created with an earlier, incompatible version of LandInG.\n",
      "Delete file or change 'harvested_fraction_filename' in landuse_setup.R"
    )
  }
  if (atts[["LandInG_version"]] != LandInG_setup$LandInG_version) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "File ",
      sQuote(LandInG_setup$landuse$harvested_fraction_filename),
      " was created with a different version of LandInG.\n",
      "Delete file to process again."
    )
  }
  # Check that crop names match
  if (
    any(
      ncdf4::ncvar_get(harvested_fraction_file, "crop") !=
        dimnames(country_env$fao_mon_production_array)[["item"]]
    )
  ) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "Crop names in ",
      sQuote(LandInG_setup$landuse$harvested_fraction_filename),
      " do not match names in fao_mon_production_array"
    )
  }
  # Check that spatial resolution matches
  if (
    harvested_fraction_file$dim$lon$len !=
      terra::ncol(country_env$ram_gadm_cropland) ||
      harvested_fraction_file$dim$lat$len !=
        terra::nrow(country_env$ram_gadm_cropland)
  ) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "Dimensions in ",
      sQuote(LandInG_setup$landuse$harvested_fraction_filename),
      " do not match dimensions of ram_gadm_cropland"
    )
  }
  if (
    harvested_fraction_file$dim$time$len !=
      terra::nlyr(country_env$ram_gadm_cropland)
  ) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "Number of years in ",
      sQuote(LandInG_setup$landuse$harvested_fraction_filename),
      " does not match mon_refyear"
    )
  }
  unit <- harvested_fraction_file$dim$time$units
  ref_year <- as.integer(
    format.Date(gsub("days|years since ", "", unit), "%Y")
  )
  if (
    any(
      harvested_fraction_file$dim$time$vals + ref_year !=
        LandInG_setup$landuse$mon_refyear
    )
  ) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "Mismatch between year(s) in ",
      sQuote(LandInG_setup$landuse$harvested_fraction_filename),
      toString(harvested_fraction_file$dim$time$vals + ref_year),
      " and mon_refyear ", toString(LandInG_setup$landuse$mon_refyear)
    )
  }
}
# Gap-fill statistics are saved to RData file. Reuse if it exists already.
if (
  file.exists(LandInG_setup$landuse$harvested_fraction_fill_statistics_RData)
) {
  cat(
    "Loading gap-filling statistics from previous script run from",
    sQuote(LandInG_setup$landuse$harvested_fraction_fill_statistics_RData), "\n"
  )
  load(LandInG_setup$landuse$harvested_fraction_fill_statistics_RData)
  if (
    !exists("LandInG_version") ||
      LandInG_version != LandInG_setup$LandInG_version
  ) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "Data in existing ",
      sQuote(LandInG_setup$landuse$harvested_fraction_fill_statistics_RData),
      " was generated with a different version of LandInG.\n",
      "Delete file to process again."
    )
  }
  rm(LandInG_version)
} else {
  # Set up gap-fill statistics if they do not exist yet
  # This counts the number of districts which have been gap-filled with data
  # from the same district, same state or same country (or could not be gap-
  # filled at all)
  copydim <- c("country", "item", "time")
  fill_statistics <- array(
    dim = c(dim(country_env$fao_mon_production_array)[copydim], level = 4),
    dimnames = c(
      dimnames(country_env$fao_mon_production_array)[copydim],
      list(level = c("country", "state", "district", "unsuccessful"))
    )
  )
}
for (crop in seq_len(dim(country_env$fao_mon_production_array)["item"])) {
  if (exists("mon_filedata")) {
    rm(mon_filedata)
  }
  # Crop name in fao_mon_production_array (usually FAOSTAT name)
  fao_crop <- dimnames(country_env$fao_mon_production_array)[["item"]][crop]
  if (fao_crop %in% unique(fao_production_item_group_def$Item.Group)) {
    # FAOSTAT group crop, no need to gap-fill
    message("*** Skipping FAOSTAT group crop ", sQuote(fao_crop), " ***")
    next
  }
  # FAOSTAT item code corresponding to fao_crop
  codelist <- c(
    fao_production_item_group_def$Item.Code,
    fao_production_item_def$Item.Code
  )
  index <- match(
    fao_crop,
    c(
      fao_production_item_group_def$Item,
      fao_production_item_def$Item
    )
  )
  fao_item_code <- codelist[index]
  if (
    !is.na(fao_item_code) && !fao_item_code %in% crop_type_mapping$FAO.item.code
  ) {
    # FAOSTAT crop that is not covered by Monfreda. No pattern to process.
    # Check if FAOSTAT crop may be listed in fao_reassign as using the pattern
    # of a different crop.
    if (!fao_crop %in% names(fao_reassign)) {
      # No pattern to process.
      message(
        "*** Skipping FAOSTAT crop ", sQuote(fao_crop),
        " because it is not included in Monfreda ***"
      )
      next
    }
  } else {
    cat("*** Processing", sQuote(fao_crop), "***\n")
  }
  # Load data field of gap-filled fraction from NetCDF.
  # This is empty after the file has been created for the first time.
  fao_mon_fraction <- ncdf4::ncvar_get(
    nc = harvested_fraction_file,
    varid = "harvested_fraction",
    start = c(1, 1, crop, 1),
    count = c(-1, -1, 1, -1)
  )
  # Dissolve separate lon and lat dimensions
  fao_mon_fraction <- array(
    fao_mon_fraction,
    dim = c(
      cell = ncol(fao_mon_fraction) * nrow(fao_mon_fraction),
      time = harvested_fraction_file$dim$time$len
    ),
    dimnames = list(
      cell = NULL,
      time = LandInG_setup$landuse$mon_refyear
    )
  )
  if (fao_crop %in% names(fao_reassign)) {
    # Use pattern(s) from different crop(s)
    cat(
      "*** Using FAOSTAT crop(s)", toString(sQuote(fao_reassign[[fao_crop]])),
      "as a proxy for", sQuote(fao_crop), "***\n"
    )
    fao_crop <- fao_reassign[[fao_crop]]
    index <- match(
      fao_crop,
      c(
        fao_production_item_group_def$Item,
        fao_production_item_def$Item
      )
    )
    fao_item_code <- codelist[index]
  }
  # Find Monfreda crop matching fao_crop
  # If crop has a FAOSTAT item code use that to find Monfreda name, otherwise
  # search directly for Monfreda name
  index <- ifelse(
    is.na(fao_item_code),
    match(fao_crop, crop_type_mapping$Monfreda),
    match(fao_item_code, crop_type_mapping$FAO.item.code)
  )
  # Monfreda name of crop(s) to use
  mon_crop <- crop_type_mapping$Monfreda[index]
  if (anyNA(mon_crop)) {
    ncdf4::nc_close(harvested_fraction_file)
    stop(
      "Could not determine Monfreda crop(s) for fao_crop ",
      toString(sQuote(fao_crop))
    )
  }
  # Load Monfreda harvested area pattern(s) for mon_crop
  # Function get_crop_monfreda() defined in helper/get_crop_monfreda.R
  if (length(mon_crop) > 1) {
    # More than one source crop
    for (c in mon_crop) {
      loaded_fields <- get_crop_monfreda(
        filename = mon_filenames[c],
        file_format = LandInG_setup$landuse$mon_fmt,
        file_area_layer = LandInG_setup$landuse$mon_area_layer,
        file_quality_layer = LandInG_setup$landuse$mon_area_quality_layer,
        file_is_fraction = mon_is_fraction,
        file_var = LandInG_setup$landuse$mon_file_var,
        file_units = LandInG_setup$landuse$mon_area_units,
        file_years = LandInG_setup$landuse$mon_refyear,
        crop = c,
        unit_raster = country_env$ram_gadm_cropland,
        fact = mon2gadm,
        global_cover = global_extent,
        area_raster = country_env$mon_area,
        crop_names = LandInG_setup$landuse$mon_names
      )
      if (exists("mon_filedata")) {
        # Append crop to mon_filedata if length of mon_crop > 1 and
        # this is not the first source crop
        tmpdata <- array(
          loaded_fields[["filedata"]],
          dim = c(dim(loaded_fields[["filedata"]]), item = 1),
          dimnames = c(
            dimnames(loaded_fields[["filedata"]]),
            list(item = c)
          )
        )
        mon_filedata <- abind::abind(
          mon_filedata,
          tmpdata,
          along = length(dim(tmpdata)),
          use.dnns = TRUE
        )
        # Fix dimension names after abind.
        tmpdimn <- dimnames(mon_filedata)
        names(tmpdimn) <- names(dim(tmpdata))
        names(dim(mon_filedata)) <- names(dim(tmpdata))
        dimnames(mon_filedata) <- tmpdimn
        rm(tmpdata)
      } else {
        # Set mon_filedata to data loaded from file
        mon_filedata <- array(
          loaded_fields[["filedata"]],
          dim = c(dim(loaded_fields[["filedata"]]), item = 1),
          dimnames = c(
            dimnames(loaded_fields[["filedata"]]),
            list(item = c)
          )
        )
      }
      rm(loaded_fields)
    }
  } else {
    # Only one source crop
    loaded_fields <- get_crop_monfreda(
      filename = mon_filenames[mon_crop],
      file_format = LandInG_setup$landuse$mon_fmt,
      file_area_layer = LandInG_setup$landuse$mon_area_layer,
      file_quality_layer = LandInG_setup$landuse$mon_area_quality_layer,
      file_is_fraction = mon_is_fraction,
      file_var = LandInG_setup$landuse$mon_file_var,
      file_units = LandInG_setup$landuse$mon_area_units,
      file_years = LandInG_setup$landuse$mon_refyear,
      crop = mon_crop,
      unit_raster = country_env$ram_gadm_cropland,
      fact = mon2gadm,
      global_cover = global_extent,
      area_raster = country_env$mon_area,
      crop_names = LandInG_setup$landuse$mon_names
    )
    mon_filedata <- array(
      loaded_fields[["filedata"]],
      dim = c(dim(loaded_fields[["filedata"]]), item = 1),
      dimnames = c(
        dimnames(loaded_fields[["filedata"]]),
        list(item = mon_crop)
      )
    )
    rm(loaded_fields)
  }
  # Remove very small values from Monfreda source data.
  # Threshold mon_cutoff defined in landuse_setup.R
  tiny <- which(mon_filedata < LandInG_setup$landuse$mon_cutoff)
  mon_filedata[tiny] <- 0

  # Dissolve separate lon and lat dimensions
  mon_filedata <- array(
    mon_filedata,
    dim = c(
      cell = unname(nrow(mon_filedata) * ncol(mon_filedata)),
      time = unname(dim(mon_filedata)["time"]),
      item = unname(dim(mon_filedata)["item"])
    ),
    dimnames = c(
      list(cell = NULL),
      dimnames(mon_filedata)[c("time", "item")]
    )
  )

  # Calculate crop area as fraction of cropland
  mon_fraction <- ifelse(
    rep(
      terra::values(country_env$ram_gadm_cropland, mat = FALSE),
      dim(mon_filedata)["item"]
    ) > 0,
    mon_filedata / rep(
      terra::values(country_env$ram_gadm_cropland, mat = FALSE),
      dim(mon_filedata)["item"]
    ),
    NA
  )
  dim(mon_fraction) <- dim(mon_filedata)
  dimnames(mon_fraction) <- dimnames(mon_filedata)
  rm(mon_filedata)

  # Gap-filling is done on a country-by-country basis
  for (country in dimnames(country_env$fao_mon_production_array)[["country"]]) {
    if (country %in% names(fao_groups)) {
      # No need to process country groups
      next
    }
    if (country %in% names(LandInG_setup$landuse$compound_countries)) {
      # Countries that seize to exist at some point in time ->
      # run for parts instead of compound country
      next
    }
    country_cells <- country_env$fao_gadm_country_cells[[country]]
    if (is.null(country_cells) || length(country_cells) == 0) {
      # No need to process countries with no associated cells
      next
    }
    # Remove pattern artefacts
    # Check if crop is listed in fao_mon_use_pattern.
    # Crop may been re-assigned or have more than one source crop,
    # check each one.
    for (c in seq_len(dim(mon_fraction)["item"])) {
      # Index refers to actual source
      index <- ifelse(
        dimnames(country_env$fao_mon_production_array)[["item"]][crop] %in%
          names(fao_reassign) & dim(mon_fraction)["item"] > 1,
        fao_reassign[[
          dimnames(country_env$fao_mon_production_array)[["item"]][crop]
        ]][c],
        dimnames(country_env$fao_mon_production_array)[["item"]][crop]
      )
      for (year in seq_along(LandInG_setup$landuse$mon_refyear)) {
        if (!country_env$fao_mon_use_pattern[country, index, year]) {
          # Remove existing pattern in mon_fraction in country if
          # fao_mon_use_pattern is FALSE
          mon_fraction[country_cells, year, c] <- NA
          # Reset gap-filling statistics if fao_mon_use_pattern has changed
          # from previous script run
          fill_statistics[country, crop, year, ] <- NA
          # Reset gap-filled pattern if fao_mon_use_pattern has changed
          # from previous script run
          fao_mon_fraction[country_cells, year] <- NA
        }
      }
    }
    # If combining several patterns, sum up fractions
    if (dim(mon_fraction)["item"] > 1) {
      # Multiple source crops
      fao_mon_fraction[country_cells, ] <- ifelse(
        # Check in each cell if any mon_fraction is not NA
        apply(
          mon_fraction[country_cells, , , drop = FALSE],
          c("cell", "time"),
          function(x) all(is.na(x))
        ),
        # Keep original value of fao_mon_fraction (NA) if source pattern is NA
        fao_mon_fraction[country_cells, ],
        # Otherwise sum up source crop patterns
        apply(
          mon_fraction[country_cells, , , drop = FALSE],
          c("cell", "time"),
          sum,
          na.rm = TRUE
        )
      )
    } else {
      # One single source crop
      fao_mon_fraction[country_cells, ] <- ifelse(
        # Check in each cell if mon_fraction is not NA
        is.na(mon_fraction[country_cells, , ]),
        # Keep original value of fao_mon_fraction (NA) if source pattern is NA
        fao_mon_fraction[country_cells, ],
        # Otherwise use source crop pattern
        mon_fraction[country_cells, , ]
      )
    }
    # Spatial gap-filling
    if (all(is.na(fao_mon_fraction[country_cells, ]))) {
      # All cells are NA, no need to try gap-filling
      next
    }
    for (year in seq_along(LandInG_setup$landuse$mon_refyear)) {
      # Grid cells with HYDE cropland but without Ramankutty cropland in
      # country_cells
      index <- which(
        hyde_max_cropland[country_cells] > 0 &
          (is.na(country_env$ram_gadm_cropland[[year]][country_cells]) |
             country_env$ram_gadm_cropland[[year]][country_cells] == 0)
      )
      fill_cells <- country_cells[index]
      # Gap-fill statistics just for country
      fill_success <- fill_statistics[country, crop, year, ]
      if (all(is.na(fill_success))) {
        # First script run, initialize
        fill_success[] <- 0
        # Set "unsuccessful" counter to the total number of districts
        fill_success["unsuccessful"] <-
          length(unique(gadmlevel_raster[fill_cells][, "district"]))
      }
      # No need to fill gaps which have already been filled in
      # fao_mon_fraction in previous script runs:
      # Filter with actual NA values
      fill_cells <- fill_cells[which(is.na(fao_mon_fraction[fill_cells, year]))]
      if (length(fill_cells) > 0) {
        # Get GADM administrative units level 0-2 for fill_cells
        # Gap-filling first tries level 2, then level 1, then level 0 until it
        # is successful.
        fill_gadmlevels <- gadmlevel_raster[fill_cells]
        # Matrix with cell index and corresponding GADM level 0-2 codes
        country_gadmlevels <- cbind(
          global = country_cells,
          gadmlevel_raster[country_cells]
        )
        cat(
          "Trying to fill in gaps in",
          length(unique(fill_gadmlevels[, "district"])),
          "out of",
          length(unique(gadmlevel_raster[country_cells][, "district"])),
          "districts of", country, "\n"
          # This counts all districts with missing cells no matter whether only
          # one cell is missing or all cells are missing.
        )
        # Loop over all districts that have at least one cell requiring gap-
        # filling.
        for (district in unique(fill_gadmlevels[, "district"])) {
          fillvalue <- NA
          district_index <- which(country_gadmlevels[, "district"] == district)
          cell_index <- country_gadmlevels[district_index, "global"]
          district_cropland <- country_env$ram_gadm_cropland[[year]][cell_index]
          # Check if any cell in district has Ramankutty cropland (and therefore
          # should have a Monfreda pattern)
          if (max(district_cropland, na.rm = TRUE) > 0) {
            fillvalue <- sum(
              fao_mon_fraction[cell_index, year] * district_cropland,
              na.rm = TRUE
            ) / sum(district_cropland, na.rm = TRUE)
            # Increase counter for districts gap-filled with data from same
            # district
            fill_success["district"] <- fill_success["district"] + 1
            # Decrease counter for districts that could not be gap-filled
            fill_success["unsuccessful"] <- fill_success["unsuccessful"] - 1
          } else {
            # Try state level next
            index <- which(fill_gadmlevels[, "district"] == district)
            state <- unique(fill_gadmlevels[index, "state"])
            state_index <- which(country_gadmlevels[, "state"] %in% state)
            cell_index <- country_gadmlevels[state_index, "global"]
            state_cropland <- country_env$ram_gadm_cropland[[year]][cell_index]
            # Check if any cell in state has Ramankutty cropland (and therefore
            # should have a Monfreda pattern)
            if (max(state_cropland, na.rm = TRUE) > 0) {
              fillvalue <- sum(
                fao_mon_fraction[cell_index, year] * state_cropland,
                na.rm = TRUE
              ) / sum(state_cropland, na.rm = TRUE)
              # Increase counter for districts gap-filled with data from same
              # state
              fill_success["state"] <- fill_success["state"] + 1
              # Decrease counter for districts that could not be gap-filled
              fill_success["unsuccessful"] <- fill_success["unsuccessful"] - 1
            } else {
              # Try country level next
              index <- which(fill_gadmlevels[, "state"] %in% state)
              ccode <- unique(fill_gadmlevels[index, "country"])
              country_index <- which(country_gadmlevels[, 2] %in% ccode)
              cell_index <- country_gadmlevels[country_index, "global"]
              country_cropland <- country_env$ram_gadm_cropland[[year]][cell_index]
              if (max(country_cropland, na.rm = TRUE) > 0) {
                fillvalue <- sum(
                  fao_mon_fraction[cell_index, year] * country_cropland,
                  na.rm = TRUE
                ) / sum(country_cropland, na.rm = TRUE)
                # Increase counter for districts gap-filled with data from same
                # country
                fill_success["country"] <- fill_success["country"] + 1
                # Decrease counter for districts that could not be gap-filled
                fill_success["unsuccessful"] <- fill_success["unsuccessful"] - 1
              } else {
                fillvalue <- NA
              }
              rm(country_index, country_cropland)
            }
            rm(state_index, state_cropland)
          }
          rm(district_index, district_cropland)
          # Set all grid cells in the district that require gap-filling to
          # derived fillvalue.
          fillindex <- fill_cells[which(fill_gadmlevels[, "district"] == district)]
          fao_mon_fraction[fillindex, year] <- fillvalue
        }
        # Print out gap-filling statistics for country
        if (length(LandInG_setup$landuse$mon_refyear) > 1) {
          cat(
            "Monfreda reference year:",
            LandInG_setup$landuse$mon_refyear[year],
            "\n"
          )
        }
        cat(
          sum(fill_success[c("district", "state", "country")]),
          "districts gap-filled,",
          fill_success["district"], "with data at the district level,",
          fill_success["state"], "with data at the state level, and",
          fill_success["country"], "with data at the country level\n"
        )
        # Save for statistics RData file
        fill_statistics[country, crop, year, ] <- fill_success
      }
      # Update fao_mon_use_pattern depending on whether any cells contain
      # values.
      cropname <- dimnames(country_env$fao_mon_production_array)[["item"]][crop]
      country_env$fao_mon_use_pattern[country, cropname, year] <-
        any(fao_mon_fraction[country_cells, year] > 0, na.rm = TRUE)
    } # end of year loop Monfreda years
  } # end of country loop
  # Update fao_mon_use_pattern for compound countries
  cropname <- dimnames(country_env$fao_mon_production_array)[["item"]][crop]
  clist <- intersect(
    names(LandInG_setup$landuse$compound_countries),
    dimnames(country_env$fao_mon_use_pattern)[["country"]]
  )
  for (country in clist) {
    # Set compound country to TRUE if at least one of the countries in it is
    # TRUE
    countries <- LandInG_setup$landuse$compound_countries[[country]]
    country_env$fao_mon_use_pattern[country, cropname, ] <- apply(
      country_env$fao_mon_use_pattern[countries, cropname, , drop = FALSE],
      "time",
      any,
      na.rm = TRUE
    )
  }
  # Save gap-filled pattern to NetCDF file
  ncdf4::ncvar_put(
    nc = harvested_fraction_file,
    varid = "harvested_fraction",
    vals = c(fao_mon_fraction),
    start = c(1, 1, crop, 1),
    count = c(-1, -1, 1, -1)
  )
  ncdf4::nc_sync(harvested_fraction_file)
  # Save gap-filling statistics to RData file
  LandInG_version <- LandInG_setup$LandInG_version
  save(
    fill_statistics,
    LandInG_version,
    file = LandInG_setup$landuse$harvested_fraction_fill_statistics_RData
  )
} # end of crop loop

# Finish files generated by this script
ncdf4::nc_close(harvested_fraction_file)
LandInG_version <- LandInG_setup$LandInG_version
save(
  fill_statistics,
  LandInG_version,
  file = LandInG_setup$landuse$harvested_fraction_fill_statistics_RData
)
rm(LandInG_version)
# Update country sums of matching Monfreda and FAOSTAT crops because
# fao_mon_use_pattern may have changed.
# This is first created by country_level_data.R
# Indicate that file has been processed by harvested_fraction.R
country_env$harvested_fraction_processed <- TRUE
# Update LandInG_version
country_env$LandInG_version <- LandInG_setup$LandInG_version
# Wrap SpatRaster objects before saving to file
for (obj in names(country_env)) {
  if (is(country_env[[obj]], "SpatRaster")) {
    country_env[[obj]] <- terra::wrap(country_env[[obj]])
  }
}
save(
  list = union(fao_mon_country_objects, "LandInG_version"),
  file = LandInG_setup$landuse$fao_mon_country_RData,
  envir = country_env
)
################################################################################
