################################################################################
## Copyright (C) 2022 Potsdam Institute for Climate Impact Research (PIK),    ##
## see COPYRIGHT file.                                                        ##
##                                                                            ##
## This file is part of LandInG and licensed under GNU AGPL Version 3 or      ##
## later. See LICENSE file or go to http://www.gnu.org/licenses/              ##
## Contact: https://github.com/PIK-LPJmL/LandInG/                             ##
################################################################################

################################################################################
## This file takes manure application from file and converts it into rate per ##
## cropland area. The default manure application rate dataset Zhang et al.    ##
## (2017) provides application rates normalized to total grid cell area and   ##
## is rescaled by this script.                                                ##
## This script also supports manure application source files that provide     ##
## total absolute manure amount per cell and converts them into rate per      ##
## cropland area.                                                             ##
################################################################################

# Clean up memory
rm(list = ls(all = TRUE))

################################################################################
## Setup of variables valid across all scripts related to fertilizer data     ##
## processing.                                                                ##
## - sets many directories and file names                                     ##
source("fertilizer_setup.R")
## Missing value used in NetCDF files generated by this script.               ##
missval_float <- 1e20
################################################################################


################################################################################
## Determine source file characteristics and required conversion.             ##
## Carry out conversion and save file to resolution-specific working directory##
for (nut in LandInG_setup$fertilizer$manure_nutrients) {
  # Detect available file(s).
  # Note: By default, manure is only available for nitrogen, and manure_*
  # parameters in fertilizer_setup.R all refer to nitrogen. However, this script
  # technically supports setting values per nutrient by giving named vectors as
  # manure_* settings.
  search_dir <- dirname(
    ifelse(
      length(LandInG_setup$fertilizer$manure_src_name) > 1,
      LandInG_setup$fertilizer$manure_src_name[nut],
      LandInG_setup$fertilizer$manure_src_name
    )
  )
  name_pattern <- basename(
    ifelse(
      length(LandInG_setup$fertilizer$manure_src_name) > 1,
      LandInG_setup$fertilizer$manure_src_name[nut],
      LandInG_setup$fertilizer$manure_src_name
    )
  )
  src_filename <- list.files(
    search_dir,
    pattern = name_pattern,
    full.names = TRUE
  )
  if (length(src_filename) == 0) {
    stop(
      "Cannot detect source file for nutrient ", sQuote(nut),
      ". Used search pattern: ",
      sQuote(
        gsub(
          "\\", "\\\\",
          ifelse(
            length(LandInG_setup$fertilizer$manure_src_name) > 1,
            LandInG_setup$fertilizer$manure_src_name[nut],
            LandInG_setup$fertilizer$manure_src_name
          ),
          fixed = TRUE
        )
      )
    )
  } else if (length(src_filename) > 1) {
    warning(
      "Detected ", length(src_filename),
      " source files for nutrient ", sQuote(nut),
      " matching search pattern ",
      sQuote(
        gsub(
          "\\", "\\\\",
          ifelse(
            length(LandInG_setup$fertilizer$manure_src_name) > 1,
            LandInG_setup$fertilizer$manure_src_name[nut],
            LandInG_setup$fertilizer$manure_src_name
          ),
          fixed = TRUE
        )
      ),
      ":\n", toString(src_filename),
      call. = FALSE,
      immediate. = TRUE
    )
  }
  # Is reference area specified?
  nut_is_rate <- !is.null(LandInG_setup$fertilizer$manure_ref_area) &&
    (length(LandInG_setup$fertilizer$manure_ref_area) == 1 &&
       is.null(names(LandInG_setup$fertilizer$manure_ref_area)) ||
       nut %in% names(LandInG_setup$fertilizer$manure_ref_area))
  # Confirm that unit is absolute amount if manure is not a rate
  nut_src_unit <- ifelse(
    length(LandInG_setup$fertilizer$manure_src_unit) > 1,
    LandInG_setup$fertilizer$manure_src_unit[nut],
    LandInG_setup$fertilizer$manure_src_unit
  )
  if (!nut_is_rate && !units::ud_are_convertible(nut_src_unit, "kg")) {
    stop(
      "You have set manure_ref_area to NULL, which suggests that manure data ",
      "represents total amount. However, cannot recognize manure_src_unit ",
      sQuote(nut_src_unit), " as a unit specifying total mass."
    )
  }
  # Confirm that manure_src_unit can be converted into manure_rate_unit if
  # manure is given as a rate.
  nut_rate_unit <- ifelse(
    length(LandInG_setup$fertilizer$manure_rate_unit) > 1,
    LandInG_setup$fertilizer$manure_rate_unit[nut],
    LandInG_setup$fertilizer$manure_rate_unit
  )
  if (nut_is_rate && !units::ud_are_convertible(nut_src_unit, nut_rate_unit)) {
    stop(
      "Cannot convert manure_src_unit ", sQuote(nut_src_unit),
      " into manure_rate_unit ", sQuote(nut_rate_unit)
    )
  }
  # Confirm that manure_rate_unit is actually a mass per area rate.
  if (!units::ud_are_convertible(nut_rate_unit, "g/m2")) {
    stop(
      "Provided manure_rate_unit ", sQuote(nut_rate_unit),
      " does not seem to be a valid mass per unit area."
    )
  }
  # Derive mass component of manure_src_unit
  nut_src_mass_unit <- regmatches(
    nut_src_unit,
    regexpr("^[a-zA-Z]+", nut_src_unit)
  )
  # Derive mass component and area component from manure_rate_unit
  nut_output_mass_unit <- regmatches(
    nut_rate_unit,
    regexpr("^[a-zA-Z]+", nut_rate_unit)
  )
  # This can detect km2, m2 or hectare. If your source data uses a different
  # unit you need to expand the search.
  nut_output_area_unit <- ifelse(
    grepl("km-2|/[ ]?km2", nut_rate_unit),
    "km2",
    ifelse(
      grepl("m-2|/[ ]?m2", nut_rate_unit),
      "m2",
      ifelse(
        grepl("ha-1|/[ ]?ha", nut_rate_unit),
        "ha",
        stop(paste("Cannot detect area unit from", sQuote(nut_rate_unit)))
      )
    )
  )
  if (!units::ud_are_convertible(nut_src_mass_unit, "kg")) {
    stop(
      "Cannot detect unit specifying mass in manure_src_unit ",
      sQuote(nut_src_unit)
    )
  }
  if (!units::ud_are_convertible(nut_output_mass_unit, "kg")) {
    stop(
      "Cannot detect unit specifying mass in manure_rate_unit ",
      sQuote(nut_rate_unit)
    )
  }
  if (nut_is_rate) {
    # Detect area component of nut_src_unit. This can detect km2, m2 or hectare.
    # If your source data uses a different unit you need to expand the search.
    nut_src_area_unit <- ifelse(
      grepl("km-2|/[ ]?km2", nut_src_unit),
      "km2",
      ifelse(
        grepl("m-2|/[ ]?m2", nut_src_unit),
        "m2",
        ifelse(
          grepl("ha-1|/[ ]?ha", nut_src_unit),
          "ha",
          stop(paste("Cannot detect area unit from", sQuote(nut_src_unit)))
        )
      )
    )
  } else  {
    # Detect area component of nut_rate_unit. This can detect km2, m2 or
    # hectare. If your source data uses a different unit you need to expand the
    # search. Use output rate instead of source unit if source unit is not a
    # rate.
    nut_src_area_unit <- ifelse(
      grepl("km-2|/[ ]?km2", nut_rate_unit),
      "km2",
      ifelse(
        grepl("m-2|/[ ]?m2", nut_rate_unit),
        "m2",
        ifelse(
          grepl("ha-1|/[ ]?ha", nut_rate_unit),
          "ha",
          stop(paste("Cannot detect area unit from", sQuote(nut_rate_unit)))
        )
      )
    )
  }
  # Area reference. "grid" or "cropland" if nut_is_rate.
  if (!is.null(LandInG_setup$fertilizer$manure_ref_area)) {
    if (is.null(names(LandInG_setup$fertilizer$manure_ref_area)) &&
        length(LandInG_setup$fertilizer$manure_ref_area) == 1) {
      nut_ref_area <- LandInG_setup$fertilizer$manure_ref_area
    } else if (nut %in% names(LandInG_setup$fertilizer$manure_ref_area)) {
      nut_ref_area <- LandInG_setup$fertilizer$manure_ref_area[nut]
    } else {
      nut_ref_area <- NULL
    }
  } else {
    nut_ref_area <- NULL
  }
  # Optional maximum application rate.
  nut_threshold <- ifelse(
    is.null(LandInG_setup$fertilizer$manure_threshold),
    Inf,
    ifelse(
      is.null(names(LandInG_setup$fertilizer$manure_threshold)) &&
        length(LandInG_setup$fertilizer$manure_threshold) == 1,
      LandInG_setup$fertilizer$manure_threshold,
      ifelse(
        nut %in% names(LandInG_setup$fertilizer$manure_threshold),
        LandInG_setup$fertilizer$manure_threshold[nut],
        Inf
      )
    )
  )
  nut_threshold_res <- ifelse(
    is.null(names(LandInG_setup$fertilizer$manure_threshold_res)) &&
      length(LandInG_setup$fertilizer$manure_threshold_res) == 1,
    LandInG_setup$fertilizer$manure_threshold_res,
    ifelse(
      nut %in% names(LandInG_setup$fertilizer$manure_threshold_res),
      LandInG_setup$fertilizer$manure_threshold_res[nut],
      stop("Missing setting manure_threshold_res[", dQuote(nut), "]")
    )
  )
  if (is.finite(nut_threshold) && nut_threshold_res == "source") {
    cat(
      "Applying manure_threshold of", nut_threshold, nut_rate_unit,
      "and removing all manure above threshold.\n"
    )
  }
  if ((!is.null(nut_ref_area) && nut_ref_area == "grid") || !nut_is_rate ||
      (is.finite(nut_threshold) && nut_threshold_res == "source")
  ) {
    # Need cropland dataset to scale manure rates referring to full grid area to
    # cropland area, or to scale absolute amounts to rate per cropland area.
    if (!is.null(LandInG_setup$fertilizer$manure_cropland_name)) {
      if (is.null(names(LandInG_setup$fertilizer$manure_cropland_name)) &&
          length(LandInG_setup$fertilizer$manure_cropland_name) == 1) {
        nut_cropland_name <- LandInG_setup$fertilizer$manure_cropland_name
      } else if (nut %in% names(LandInG_setup$fertilizer$manure_cropland_name)) {
        nut_cropland_name <- LandInG_setup$fertilizer$manure_cropland_name[nut]
      } else {
        nut_cropland_name <- NULL
      }
    } else {
      nut_cropland_name <- NULL
    }
    nut_cropland_varname <- ifelse(
      is.null(names(LandInG_setup$fertilizer$manure_cropland_varname)) &&
        length(LandInG_setup$fertilizer$manure_cropland_varname) == 1,
      LandInG_setup$fertilizer$manure_cropland_varname,
      LandInG_setup$fertilizer$manure_cropland_varname[nut]
    )
    nut_cropland_unit <- ifelse(
      is.null(names(LandInG_setup$fertilizer$manure_cropland_unit)) &&
        length(LandInG_setup$fertilizer$manure_cropland_unit) == 1,
      LandInG_setup$fertilizer$manure_cropland_unit,
      LandInG_setup$fertilizer$manure_cropland_unit[nut]
    )
    if (is.null(nut_cropland_name) || !file.exists(nut_cropland_name)) {
      if (nut_is_rate) {
        stop(
          "You have set 'manure_ref_area' to ",
          sQuote(nut_ref_area),
          ". Please specify a valid 'manure_cropland_name' to use as ",
          "cropland extent."
        )
      } else {
        stop(
          "You have set manure_src_unit to be an absolute amount. ",
          "Please specify a valid 'manure_cropland_name' to use as cropland ",
          "extent."
        )
      }
    }
    if (nut_is_rate && nut_ref_area == "grid") {
      cat(
        "Manure", nut, "is scaled to 'grid' and needs to be rescaled to",
        "cropland area. Fetching cropland file", sQuote(nut_cropland_name), "\n"
      )
    } else if (is.finite(nut_threshold) && nut_threshold_res == "source") {
      cat(
        "Manure", nut, "is scaled to 'cropland' and a manure_threshold is",
        "set. Fetching cropland file", sQuote(nut_cropland_name),
        "to allow conversion of application rates to absolute amounts.\n"
      )
    } else {
      cat(
        "Manure", nut, "is provided as total amount and needs to be scaled",
        "to cropland area.  Fetching cropland file", sQuote(nut_cropland_name),
        "\n"
      )
    }
    nut_cropland_nc <- ncdf4::nc_open(nut_cropland_name)
    # Get years included in cropland file. Needs to cover all years of manure
    # data.
    nut_cropland_fileyears <- nc_file_years(nut_cropland_nc)
    # Confirm that unit in file matches manure_cropland_unit
    ncunit <- ncdf4::ncatt_get(nut_cropland_nc, nut_cropland_varname, "units")
    if (ncunit$hasatt &&
        units::ud_convert(1, ncunit$value, nut_cropland_unit) != 1
    ) {
      warning(
        "Unit in manure_cropland_name ", sQuote(ncunit$value),
        " does not match defined manure_cropland_unit ",
        sQuote(nut_cropland_unit),
        ". Using ", sQuote(ncunit$value),
        call. = FALSE,
        immediate. = TRUE
      )
      nut_cropland_unit <- ncunit$value
    }
    # Check if cropland is given as area or given as cell fraction
    nut_cropland_is_relative <-
      !units::ud_are_convertible(nut_cropland_unit, "m2")
    # Determine corresponding area file.
    if (!is.null(LandInG_setup$fertilizer$manure_cropland_area_file)) {
      if (is.null(names(LandInG_setup$fertilizer$manure_cropland_area_file)) &&
          length(LandInG_setup$fertilizer$manure_cropland_area_file) == 1) {
        nut_cropland_area_file <-
          LandInG_setup$fertilizer$manure_cropland_area_file
      } else if (
        nut %in% names(LandInG_setup$fertilizer$manure_cropland_area_file)
      ) {
        nut_cropland_area_file <-
          LandInG_setup$fertilizer$manure_cropland_area_file[nut]
      } else {
        nut_cropland_area_file <- NULL
      }
    } else {
      nut_cropland_area_file <- NULL
    }
    # Check if NetCDF data needs to be flipped vertically to correspond to Y
    # axis direction used by raster package
    tmpraster <- terra::rast(
      nut_cropland_name,
      subds = nut_cropland_varname,
      lyrs = 1
    )
    lat_dim <- nut_cropland_nc$dim$lat
    nut_cropland_flip <- (lat_dim$vals[1] < lat_dim$vals[2]) !=
      (terra::yFromRow(tmpraster, 1) < terra::yFromRow(tmpraster, 2))
    # Load/generate corresponding area raster for cropland.
    cat("Fetch corresponding area for cropland data.\n")
    if (is.null(nut_cropland_area_file) || !file.exists(nut_cropland_area_file)) {
      if (!is.null(nut_cropland_area_file)) {
        warning(
          "manure_cropland_area_file ", sQuote(nut_cropland_area_file),
          " defined in fertilizer_setup.R does not exist.",
          call. = FALSE,
          immediate. = TRUE
        )
      }
      cat("Using internal calculation to derive cell area\n")
      nut_cropland_area <- terra::rast(
        extent = terra::ext(tmpraster),
        resolution = terra::res(tmpraster)
      )
      terra::values(nut_cropland_area) <- rep(
        lpjmlkit::calc_cellarea(
          terra::yFromRow(tmpraster),
          terra::xres(tmpraster),
          terra::yres(tmpraster),
          earth_radius = LandInG_setup$earthradius,
          return_unit = "m2"
        ),
          each = terra::ncol(tmpraster)
        ) * units::ud_convert(1, "m2", nut_src_area_unit)
        # By default, calc_cellarea() returns cell area in m2. Convert to area
        # unit used by manure data
      terra::units(nut_cropland_area) <- nut_src_area_unit
    } else {
      nut_cropland_area_file_unit <- ifelse(
        is.null(
          names(LandInG_setup$fertilizer$manure_cropland_area_file_unit)
        ) &&
          length(LandInG_setup$fertilizer$manure_cropland_area_file_unit) == 1,
        LandInG_setup$fertilizer$manure_cropland_area_file_unit,
        LandInG_setup$fertilizer$manure_cropland_area_file_unit[nut]
      )
      if (
        !units::ud_are_convertible(
          nut_cropland_area_file_unit,
          nut_src_area_unit
        )
      ) {
        stop(
          "Unit of manure_cropland_area_file_unit ",
          sQuote(nut_cropland_area_file_unit),
          " cannot be converted into area unit of manure data ",
          sQuote(nut_src_area_unit), " detected from ", sQuote(nut_src_unit)
        )
      }
      nut_cropland_area <- load_hyde_area(
        nut_cropland_area_file,
        fileunits = nut_cropland_area_file_unit,
        return_units = nut_src_area_unit,
        return_raster = tmpraster,
        earth_radius = LandInG_setup$earthradius,
        gextent = global_extent
      )
      nut_cropland_area <- nut_cropland_area$area
    }
    rm(tmpraster)
  }
  # Loop over manure source files
  for (nut_filename in src_filename) {
    nut_nc <- ncdf4::nc_open(nut_filename)
    # Check LandInG versions
    globalatt <- ncdf4::ncatt_get(nut_nc, 0)
    if (
      is.null(globalatt$LandInG_version) ||
        globalatt$LandInG_version != LandInG_setup$LandInG_version
    ) {
      warning(
        nut_filename, " was created with a different version of LandInG.",
        " It may not be compatible.",
        immediate. = TRUE, call. = FALSE
      )
    }
    # Determine years in NetCDF file.
    nut_fileyears <- nc_file_years(nut_nc)
    # Determine NetCDF variable name. If file contains more than one variable
    # use default name set by preprocess_manure.R. Change this if source NetCDF
    # was not put together by preprocess_manure.R and contains more than one
    # variable.
    nut_varname <- ifelse(
      length(nut_nc$var) == 1,
      names(nut_nc$var),
      # Default used by preprocess_manure.R
      paste0("manure_", nut)
    )
    # Check correct unit in NetCDF file.
    ncunit <- ncdf4::ncatt_get(nut_nc, nut_varname, "units")
    if (ncunit$hasatt &&
        !units::ud_are_convertible(ncunit$value, nut_src_unit)
    ) {
      ncdf4::nc_close(nut_nc)
      if (exists("nut_cropland_nc")) {
        ncdf4::nc_close(nut_cropland_nc)
      }
      stop(
        "Unit in file ", sQuote(nut_filename), " ", sQuote(ncunit$value),
        " does not match and cannot be converted into defined ",
        "manure_src_unit ", sQuote(nut_src_unit)
      )
    }
    if (ncunit$hasatt &&
        units::ud_convert(1, ncunit$value, nut_src_unit) != 1
    ) {
      warning(
        "Unit in file ", sQuote(nut_filename), " ",
        sQuote(ncunit$value),
        " does not match defined manure_src_unit ", sQuote(nut_src_unit),
        ".\nConverting into ", sQuote(nut_src_unit),
        call. = FALSE,
        immediate. = TRUE
      )
    }
    # Determine if conversion is necessary from NetCDF file unit to
    # manure_src_unit
    nut_read_conv <- units::ud_convert(1, ncunit$value, nut_src_unit)
    # Determine if manure source data needs to be flipped vertically to match
    # Y axis direction used by raster package
    nut_raster <- terra::rast(nut_filename, subds = nut_varname, lyrs = 1)
    nut_res <- terra::res(nut_raster)
    lat_dim <- nut_nc$dim$lat
    nut_flip <- (lat_dim$vals[1] < lat_dim$vals[2]) !=
      (terra::yFromRow(nut_raster, 1) < terra::yFromRow(nut_raster, 2))
    # Check if cropland data covers all years in manure data.
    if (exists("nut_cropland_fileyears") &&
        !all(nut_fileyears %in% nut_cropland_fileyears)
    ) {
      ncdf4::nc_close(nut_cropland_nc)
      ncdf4::nc_close(nut_nc)
      stop(
        "Cropland file ", sQuote(nut_cropland_name),
        " does not cover all years in manure source file ",
        sQuote(nut_filename)
      )
    }
    # If cropland data is needed, check that it is compatible with manure data.
    if (exists("nut_cropland_nc")) {
      nut_cropland_raster <- terra::rast(
        nut_cropland_name,
        subds = nut_cropland_varname,
        lyrs = 1
      )
      nut_cropland_res <- terra::res(nut_cropland_raster)
      cropland_2_nut <- nut_res / nut_cropland_res
      if (any(cropland_2_nut < 0.999)) {
        ncdf4::nc_close(nut_cropland_nc)
        ncdf4::nc_close(nut_nc)
        stop("Cropland data is too coarse for manure data.")
      }
      # Crop cropland to spatial extent of manure if it is larger.
      nut_cropland_raster_crop <- terra::crop(nut_cropland_raster, nut_raster)
      # Save spatial extent for later.
      nut_cropland_raster_crop_extent <- terra::ext(nut_cropland_raster_crop)
      # Check if resolution and cell boundaries match
      nut_cropland_raster_crop <- try(
        match_admin_to_data(nut_raster, nut_cropland_raster_crop, fun = sum)
      )
      if (class(nut_cropland_raster_crop) == "try-error") {
        ncdf4::nc_close(nut_cropland_nc)
        ncdf4::nc_close(nut_nc)
        stop("Manure and cropland are incompatible")
      }
      cropland_2_nut <- round(cropland_2_nut)
      # Check if cropland covers full extent of manure data.
      if (terra::ncell(nut_cropland_raster_crop) != terra::ncell(nut_raster)) {
        ncdf4::nc_close(nut_cropland_nc)
        ncdf4::nc_close(nut_nc)
        stop("Cropland does not cover full extent of manure data.")
      }
      rm(nut_cropland_raster_crop)
    }
    if (nut_is_rate && nut_ref_area == "grid") {
      cat("Manure", nut, "is given as mass per grid area. Fetch area.\n")
      if (!is.null(LandInG_setup$fertilizer$manure_area_file)) {
        if (is.null(names(LandInG_setup$fertilizer$manure_area_file)) &&
            length(LandInG_setup$fertilizer$manure_area_file) == 1) {
          nut_area_file <- LandInG_setup$fertilizer$manure_area_file
        } else if (nut %in% names(LandInG_setup$fertilizer$manure_area_file)) {
          nut_area_file <- LandInG_setup$fertilizer$manure_area_file[nut]
        } else {
          nut_area_file <- NULL
        }
      } else {
        nut_area_file <- NULL
      }

      if (is.null(nut_area_file) || !file.exists(nut_area_file)) {
        if (!is.null(nut_area_file)) {
          warning(
            "manure_area_file ", sQuote(nut_area_file),
            " defined in fertilizer_setup.R does not exist.",
            call. = FALSE,
            immediate. = TRUE
          )
        }
        cat("Using internal calculation to derive cell area\n")
        nut_area <- terra::rast(
          extent = terra::ext(nut_raster),
          resolution = terra::res(nut_raster)
        )
        terra::values(nut_area) <- rep(
          lpjmlkit::calc_cellarea(
            terra::yFromRow(nut_area),
            terra::xres(nut_area),
            terra::yres(nut_area),
            return_unit = "m2",
            earth_radius = LandInG_setup$earthradius
          ),
          each = ncol(nut_area)
        ) * units::ud_convert(1, "m2", nut_src_area_unit)
        # By default, calc_cellarea() returns cell area in m2. Convert to area
        # unit used by manure data.
        terra::units(nut_area) <- nut_src_area_unit
      } else {
        nut_area_unit <- ifelse(
          is.null(names(LandInG_setup$fertilizer$manure_area_unit)) &&
            length(LandInG_setup$fertilizer$manure_area_unit) == 1,
          LandInG_setup$fertilizer$manure_area_unit,
          LandInG_setup$fertilizer$manure_area_unit[nut]
        )
        if (!units::ud_are_convertible(nut_area_unit, nut_src_area_unit)) {
          stop(
            "Unit of manure_area_file ", sQuote(nut_area_unit),
            " cannot be converted into area unit of manure data ",
            sQuote(nut_src_area_unit), " detected from ", sQuote(nut_src_unit)
          )
        }
        nut_area <- load_hyde_area(
          nut_area_file,
          fileunits = nut_area_unit,
          return_units = nut_src_area_unit,
          return_raster = nut_raster,
          earth_radius = LandInG_setup$earthradius,
          gextent = global_extent
        )
        nut_area <- nut_area$area
      }
    }

    # Set up NetCDF output file
    lon_dim <- ncdf4::ncdim_def(
      name = "longitude",
      units = "degrees_east",
      vals = terra::xFromCol(nut_raster),
      longname = "Longitude"
    )
    lat_dim <- ncdf4::ncdim_def(
      name = "latitude",
      units = "degrees_north",
      vals = terra::yFromRow(nut_raster),
      longname = "Latitude"
    )
    time_dim <- ncdf4::ncdim_def(
      name = "time",
      units = "year",
      vals = nut_fileyears,
      unlim = TRUE
    )
    # Variable containing manure application rate normalized to cropland
    nut_output_var <- ncdf4::ncvar_def(
      name = paste0("manure_", nut, "_rate"),
      units = nut_rate_unit,
      dim = list(lon_dim, lat_dim, time_dim),
      missval = missval_float,
      longname = paste("Manure", nut, "application rate on cropland"),
      compression = 5
    )
    # Variable containing manure amount that could not be allocated, either due
    # to missing cropland or due to exceeding manure_threshold.
    nut_noalloc_var <- ncdf4::ncvar_def(
      name = paste0("manure_", nut, "_noalloc"),
      units = nut_output_mass_unit,
      dim = list(lon_dim, lat_dim, time_dim),
      missval = missval_float,
      longname = paste("Manure", nut, "amount not allocated"),
      compression = 5
    )
    nut_noalloc_global <- array(
      0,
      dim = c(length(nut_fileyears), 3),
      dimnames = list(nut_fileyears, c("scaling", "threshold", "total"))
    )
    # Create NetCDF output file
    # Determine working directory for processed manure data
    tmp_res <- ifelse(nut_res < 1 / 60, 3600, 60) * nut_res
    tmp_string <- paste(
      unique(round(tmp_res)),
      unique(ifelse(nut_res < 1 / 60, "sec", "min")),
      sep = "",
      collapse = "_by_"
    )
    nut_output_dir <- file.path("tmp", paste0("work_", tmp_string))
    if (!dir.exists(nut_output_dir)) {
      dir.create(nut_output_dir, recursive = TRUE)
    }
    rm(tmp_string, tmp_res)
    nut_output_name <- file.path(
      nut_output_dir,
      paste0(
        "manure_", nut, "_rate_",
        ifelse(
          !nut_is_rate | (!is.null(nut_ref_area) & nut_ref_area == "grid"),
          "scaled_",
          ""
        ),
        ifelse(
          is.finite(nut_threshold) & nut_threshold_res == "source",
          "limited_",
          ""
        ),
        paste(range(nut_fileyears), collapse = "-"),
        ".nc"
      )
    )
    # File name for PDF plot with global statistics of non-allocated manure
    nut_output_stats_name <- file.path(
      nut_output_dir,
      paste0(
        "manure_", nut, "_rate_",
        ifelse(
          !nut_is_rate | (!is.null(nut_ref_area) & nut_ref_area == "grid"),
          "scaled_",
          ""
        ),
        ifelse(
          is.finite(nut_threshold) & nut_threshold_res == "source",
          "limited_",
          ""
        ),
        paste(range(nut_fileyears), collapse = "-"),
        ".csv"
      )
    )
    # Create NetCDF file
    if (file.exists(nut_output_name)) {
      cat(nut_output_name, "exists already and will be overwritten.\n")
    }
    nut_output_nc <- ncdf4::nc_create(
      filename = nut_output_name,
      vars = list(nut_output_var, nut_noalloc_var)
    )
    # Save LandInG version number in file.
    ncdf4::ncatt_put(
      nc = nut_output_nc,
      varid = 0,
      attname = "LandInG_version",
      attval = LandInG_setup$LandInG_version
    )
    for (year in nut_fileyears) {
      cat(year, "\n")
      nut_src_data <- ncdf4::ncvar_get(
        nut_nc,
        nut_varname,
        start = c(1, 1, which(nut_fileyears == year)),
        count = c(-1, -1, 1)
      )
      if (nut_flip) {
        nut_src_data <- nut_src_data[, seq(lat_dim$len, 1)]
      }
      # Make sure data is in nut_src_unit
      nut_src_data <- nut_src_data * nut_read_conv
      nut_data_unit <- nut_src_unit
      if (exists("nut_cropland_nc")) {
        nut_cropland_data <- ncdf4::ncvar_get(
          nut_cropland_nc,
          nut_cropland_varname,
          start = c(1, 1, which(nut_cropland_fileyears == year)),
          count = c(-1, -1, 1)
        )
        if (nut_cropland_flip) {
          nut_cropland_data <-
            nut_cropland_data[, seq(nut_cropland_nc$dim$lat$len, 1)]
        }
        if (nut_cropland_is_relative) {
          # Convert to cell fraction, then multiply with cell area in
          # nut_src_area_unit
          nut_cropland_data <- nut_cropland_data *
            units::ud_convert(1, nut_cropland_unit, "1") *
            ul(terra::values(nut_cropland_area))
        } else {
          # Convert area unit in cropland data to nut_src_area_unit
          nut_cropland_data <- nut_cropland_data *
            units::ud_convert(1, nut_cropland_unit, nut_src_area_unit)
        }
        if (
          any(
            c(nut_cropland_data) >
              (ul(terra::values(nut_cropland_area)) * 1.0001),
            na.rm = TRUE
          )
        ) {
          warning(
            "Values in ",
            length(
              which(
                c(nut_cropland_data) >
                  (ul(terra::values(nut_cropland_area)) * 1.0001)
              )
            ),
            " cell(s) of ", sQuote(nut_cropland_varname),
            " exceed grid cell area by up to ",
            max(
              c(nut_cropland_data) - ul(terra::values(nut_cropland_area)),
              na.rm = TRUE
            ),
            " ", nut_src_area_unit, ". Reducing to grid cell area.",
            immediate. = TRUE, call. = FALSE
          )
        }
        nut_cropland_data <- pmin(
          nut_cropland_data,
          matrix(
            ul(terra::values(nut_cropland_area)),
            nrow = terra::ncol(nut_cropland_area)
          )
        )
        # Crop to spatial extent of manure data (if necessary)
        xsubset <- which(
          terra::xFromCol(nut_cropland_raster) > terra::xmin(nut_raster) &
            terra::xFromCol(nut_cropland_raster) < terra::xmax(nut_raster)
        )
        ysubset <- which(
          terra::yFromRow(nut_cropland_raster) > terra::ymin(nut_raster) &
            terra::yFromRow(nut_cropland_raster) < terra::ymax(nut_raster)
        )
        nut_cropland_data <- nut_cropland_data[xsubset, ysubset, drop = FALSE]
        if (any(cropland_2_nut > 1)) {
          # Need to aggregate cropland to resolution of manure.
          tmpraster <- terra::rast(
            nut_cropland_raster_crop_extent,
            resolution = terra::res(nut_cropland_res)
          )
          terra::values(tmpraster) <- c(nut_cropland_data)
          tmpraster <- terra::aggregate(
            tmpraster,
            fact = rev(cropland_2_nut), # res() returns lon/lat, fact is lat/lon
            fun = sum,
            na.rm = TRUE
          )
          if (terra::global(tmpraster, sum, na.rm = TRUE) !=
              sum(nut_cropland_data, na.rm = TRUE)
          ) {
            stop("Error aggregating cropland data to manure resolution")
          }
          nut_cropland_data <- array(
            ul(terra::values(tmpraster)),
            dim = dim(nut_src_data)
          )
          rm(tmpraster)
        }
      }
      if ((!is.null(nut_ref_area) && nut_ref_area == "grid") || !nut_is_rate) {
        if (nut_is_rate) {
          # Convert rate normalized to grid to total amount
          nut_src_data <- nut_src_data * ul(terra::values(nut_area))
          nut_data_unit <- nut_src_mass_unit
        }
        # Record any manure amounts that will be lost by scaling to cropland.
        nut_noalloc_data <- array(0, dim = dim(nut_src_data))
        # Cells that will be lost
        noalloc <- which(nut_cropland_data == 0 | is.na(nut_cropland_data))
        nut_noalloc_data[noalloc] <- nut_src_data[noalloc] *
          units::ud_convert(1, nut_src_mass_unit, nut_output_mass_unit)
        nut_noalloc_global[as.character(year), "scaling"] <-
          sum(nut_noalloc_data, na.rm = TRUE)

        nut_noalloc_global[as.character(year), "total"] <- units::ud_convert(
          sum(nut_src_data, na.rm = TRUE),
          nut_src_mass_unit,
          nut_output_mass_unit
        )
        if (any(nut_noalloc_data > 0, na.rm = TRUE)) {
          cat(
            round(
              nut_noalloc_global[as.character(year), "scaling"] /
                nut_noalloc_global[as.character(year), "total"] * 100,
              1
            ),
            "% of total global manure amount lost by scaling to cropland\n"
          )
        }
        rm(noalloc)
        # Convert total amount to rate per cropland area
        nut_rate_data <- nut_src_data / nut_cropland_data
        nut_rate_data[which(nut_cropland_data == 0)] <- 0
        nut_data_unit <- paste(
          nut_src_mass_unit,
          nut_src_area_unit,
          sep = ifelse(grepl("-\\d+", nut_src_area_unit), " ", "/")
        )
        # nut_rate_data is now a rate scaled to cropland.
      } else {
        nut_rate_data <- nut_src_data
        nut_noalloc_data <- array(0, dim = dim(nut_src_data))
      }
      # Enforce manure_rate_unit for output.
      nut_output_data <- nut_rate_data *
        units::ud_convert(1, nut_data_unit, nut_rate_unit)
      # Check if manure_threshold meeds to be applied.
      if (is.finite(nut_threshold) && nut_threshold_res == "source") {
        # Apply manure_threshold to data. All manure above threshold is added to
        # nut_noalloc_data
        # Make sure nut_cropland_data is in correct unit so that rate can be
        # converted to absolute amount.
        nut_cropland_data <- nut_cropland_data *
          units::ud_convert(1, nut_src_area_unit, nut_output_area_unit)
        if (!is.null(nut_ref_area) && nut_ref_area == "cropland") {
          # Convert nut_src_data into absolute amount for comparison
          nut_noalloc_global[as.character(year), "total"] <- units::ud_convert(
            sum(nut_src_data * nut_cropland_data, na.rm = TRUE),
            nut_src_mass_unit,
            nut_output_mass_unit
          )
        }
        # Calculate absolute manure amount above manure_threshold
        nut_threshold_cutoff <- pmax(nut_output_data - nut_threshold, 0) *
          nut_cropland_data
        nut_threshold_cutoff[which(is.na(nut_threshold_cutoff))] <- 0
        nut_noalloc_global[as.character(year), "threshold"] <-
          sum(nut_threshold_cutoff)
        if (any(nut_threshold_cutoff > 0)) {
          cat(
            round(
              nut_noalloc_global[as.character(year), "threshold"] /
                nut_noalloc_global[as.character(year), "total"] * 100,
              1
            ),
            "% of total global manure amount lost by application of",
            "manure_threshold of", nut_threshold, nut_rate_unit, "\n"
          )
        }
        # Add removed amount to nut_noalloc_data
        nut_noalloc_data <- nut_noalloc_data + nut_threshold_cutoff
        # Cut-off nut_output_data
        nut_output_data[which(nut_output_data > nut_threshold)] <- nut_threshold
      }
      # Write data to file
      ncdf4::ncvar_put(
        nc = nut_output_nc,
        varid = nut_output_var$name,
        vals = c(nut_output_data),
        start = c(1, 1, which(time_dim$vals == year)),
        count = c(-1, -1, 1)
      )
      ncdf4::ncvar_put(
        nc = nut_output_nc,
        varid = nut_noalloc_var$name,
        vals = c(nut_noalloc_data),
        start = c(1, 1, which(time_dim$vals == year)),
        count = c(-1, -1, 1)
      )
    } # End of year loop
    ncdf4::nc_close(nut_nc)
    if (exists("nut_cropland_nc"))
      ncdf4::nc_close(nut_cropland_nc)
    ncdf4::nc_close(nut_output_nc)
    cat(time_dim$len, "years written to", nut_output_name, "\n")
    if (any(nut_noalloc_global[, c("scaling", "threshold")] > 0)) {
      # Rename columns of nut_noalloc_global to something more readable
      colnames(nut_noalloc_global) <- sub(
        "scaling",
        paste0("Manure amount lost by scaling [", nut_output_mass_unit, "]"),
        colnames(nut_noalloc_global)
      )
      colnames(nut_noalloc_global) <- sub(
        "threshold",
        paste0(
          "Manure amount lost by application of threshold [",
          nut_output_mass_unit, "]"
        ),
        colnames(nut_noalloc_global)
      )
      colnames(nut_noalloc_global) <- sub(
        "total",
        paste0("Total global manure amount [", nut_output_mass_unit, "]"),
        colnames(nut_noalloc_global)
      )
      # Add rownames as additional column
      nut_noalloc_global <- data.frame(
        Year = rownames(nut_noalloc_global),
        nut_noalloc_global,
        row.names = NULL,
        check.names = FALSE
      )
      # Save table to CSV file
      write.csv(nut_noalloc_global, nut_output_stats_name, row.names = FALSE)
      cat(
        "Global statistics of removed manure saved to",
        nut_output_stats_name, "\n"
      )
    }
  } # End of loop over source files
}
